# Generated by Django 3.1.4 on 2021-08-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('resolved', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=100)),
            ],
        ),
    ]
