# Generated by Django 3.2.9 on 2021-11-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20211118_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.developer'),
        ),
    ]
