# Generated by Django 3.2.9 on 2021-11-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.userprofile'),
            preserve_default=False,
        ),
    ]
